FROM golang:alpine AS builder

WORKDIR /project/generic-backend

COPY src/go.* ./

RUN go mod download

COPY src/ .
RUN go build -o /project/generic-backend/build/main .

FROM alpine:latest
COPY --from=builder /project/generic-backend/build/main /app/build/main

COPY launch.sh /app/launch.sh
RUN chmod +x /app/launch.sh

EXPOSE 8080
CMD [ "/app/launch.sh" ]