version: '3.9'

services:
  go-backend:
    build:
      context: .
      dockerfile: Dockerfile.staging
    ports:
      - "8080:8080"
    env_file:
      - .staging.env
    container_name: go-backend
    restart: unless-stopped
