// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/google/wire"
	"github.com/kallepan/go-backend/app/controller"
	"github.com/kallepan/go-backend/app/repository"
	"github.com/kallepan/go-backend/app/service"
)

// Injectors from injector.go:

func Init() *Initialization {
	systemRepositoryImpl := repository.SystemRepositoryInit()
	systemServiceImpl := service.SystemServiceInit(systemRepositoryImpl)
	systemControllerImpl := controller.SystemControllerInit(systemServiceImpl)
	initialization := NewInitialization(systemRepositoryImpl, systemServiceImpl, systemControllerImpl)
	return initialization
}

// injector.go:

var systemSvcSet = wire.NewSet(service.SystemServiceInit, wire.Bind(new(service.SystemService), new(*service.SystemServiceImpl)))

var systemCtrlrSet = wire.NewSet(controller.SystemControllerInit, wire.Bind(new(controller.SystemController), new(*controller.SystemControllerImpl)))

var systemRepoSet = wire.NewSet(repository.SystemRepositoryInit, wire.Bind(new(repository.SystemRepository), new(*repository.SystemRepositoryImpl)))
