// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/google/wire"
	"github.com/kallepan/go-backend/app/controller"
	"github.com/kallepan/go-backend/app/repository"
	"github.com/kallepan/go-backend/app/service"
)

// Injectors from injector.go:

func Init() *Initialization {
	systemRepositoryImpl := repository.SystemRepositoryInit()
	systemServiceImpl := service.SystemServiceInit(systemRepositoryImpl)
	systemControllerImpl := controller.SystemControllerInit(systemServiceImpl)
	userRepositoryImpl := repository.UserRepositoryInit()
	userServiceImpl := service.UserServiceInit(userRepositoryImpl)
	userControllerImpl := controller.UserControllerInit(userServiceImpl)
	initialization := NewInitialization(systemRepositoryImpl, systemServiceImpl, systemControllerImpl, userRepositoryImpl, userServiceImpl, userControllerImpl)
	return initialization
}

// injector.go:

// Set of providers for initialization
/* system */
var (
	systemSvcSet   = wire.NewSet(service.SystemServiceInit, wire.Bind(new(service.SystemService), new(*service.SystemServiceImpl)))
	systemCtrlrSet = wire.NewSet(controller.SystemControllerInit, wire.Bind(new(controller.SystemController), new(*controller.SystemControllerImpl)))
	systemRepoSet  = wire.NewSet(repository.SystemRepositoryInit, wire.Bind(new(repository.SystemRepository), new(*repository.SystemRepositoryImpl)))
)

/* user */
var (
	userSvcSet   = wire.NewSet(service.UserServiceInit, wire.Bind(new(service.UserService), new(*service.UserServiceImpl)))
	userCtrlrSet = wire.NewSet(controller.UserControllerInit, wire.Bind(new(controller.UserController), new(*controller.UserControllerImpl)))
	userRepoSet  = wire.NewSet(repository.UserRepositoryInit, wire.Bind(new(repository.UserRepository), new(*repository.UserRepositoryImpl)))
)
