version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - default

  app:
    image: mcr.microsoft.com/devcontainers/base:jammy
    env_file:
      - .env
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - default
    depends_on:
      - db

volumes:
  db-data:

networks:
  default:
    name: backend
