version: '3.9'
services:
  psql:
    image: postgres:16
    env_file:
      - ../.dev.env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    ports:
      - 8080:8080
    depends_on:
      - psql

volumes:
  db:
